const userList = [
  {
    id: 1,
    name: "J. K. Rowling",
    username: "JK",
    age: 21,
    nationality: "UK",
    country: "CANADA",
    friends: [
      {
        id: 2,
        name: "J. R. R. Tolkien",
        username: "JRR",
        age: 22,
        nationality: "US",
        country: "GERMANY",
        friends: [1, 3],
      },
      {
        id: 3,
        name: "Brent Weeks",
        username: "Breant",
        age: 23,
        nationality: "BD",
        country: "BANGLADESH",
        friends: [1, 2],
      },
    ],
  },
  {
    id: 2,
    name: "J. R. R. Tolkien",
    username: "JRR",
    age: 22,
    nationality: "US",
    country: "GERMANY",
    friends: [
      {
        id: 1,
        name: "J. K. Rowling",
        username: "JK",
        age: 21,
        nationality: "UK",
        country: "CANADA",
      },
      {
        id: 3,
        name: "Brent Weeks",
        username: "Breant",
        age: 23,
        nationality: "BD",
        country: "BANGLADESH",
        friends: [1, 2],
      },
    ],
  },
  {
    id: 3,
    name: "Brent Weeks",
    username: "Breant",
    age: 23,
    nationality: "BD",
    country: "BANGLADESH",
    friends: [
      {
        id: 1,
        name: "J. K. Rowling",
        username: "JK",
        age: 21,
        nationality: "UK",
        country: "CANADA",
      },
      {
        id: 2,
        name: "J. R. R. Tolkien",
        username: "JRR",
        age: 22,
        nationality: "US",
        country: "GERMANY",
        friends: [1, 3],
      },
    ],
  },
];

module.exports = { userList };
